-- CLIENTS MIGRATION SQL
-- Fecha: 2025-09-30T00:27:02.047Z

-- ========== CLIENTS ==========
INSERT INTO clients (id, name, email, phone, contact_person, company, address, payment_terms, requires_receipt, reminder_frequency, is_active, notes, company_id, client_code, secondary_email, city, state, postal_code, country, email_notifications, customer_type) VALUES
  (1, 'Juan Carlos Méndez', 'jcmendez@autopartes.mx', '(55) 5551-2345', 'Juan Carlos Méndez', 'Autopartes del Centro SA', 'Av. Insurgentes 123, CDMX', 30, true, 7, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (2, 'María González López', 'mgonzalez@manufactura.com.mx', '(33) 3334-5678', 'María González', 'Manufactura Industrial Guadalajara', 'Blvd. Tlaquepaque 456, Guadalajara', 15, true, 7, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (3, 'Roberto Silva Hernández', 'rsilva@construccion.mx', '(81) 8881-9012', 'Roberto Silva', 'Construcciones del Norte', 'Av. Universidad 789, Monterrey', 45, true, 7, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (4, 'Ana Patricia Vega', 'avega@logistica.com.mx', '(55) 5552-3456', 'Ana Patricia Vega', 'Logística Express Nacional', 'Periférico Sur 321, CDMX', 30, true, 7, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (5, 'Carlos Eduardo Morales', 'cmorales@tecnologia.mx', '(33) 3335-6789', 'Carlos Morales', 'Tecnología Avanzada SA', 'Av. Américas 654, Guadalajara', 60, true, 7, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (6, 'Ana García Martínez', 'ana.garcia@tecmex.com', '(55) 5512-3456', 'Ana García', 'Tecnología Mexicana SA', 'Av. Reforma 456, CDMX', 30, true, 7, true, 'Cliente preferencial con facturación automática', NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (7, 'Roberto Silva López', 'roberto.silva@constructora.mx', '(55) 5598-7654', 'Roberto Silva', 'Constructora del Valle', 'Insurgentes Sur 789, CDMX', 15, true, 3, true, 'Requiere facturas urgentes cada 3 días', NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (8, 'Carmen Mendoza Torres', 'carmen@comercializadora.com', '(55) 5587-4321', 'Carmen Mendoza', 'Comercializadora Norte', 'Blvd. López Mateos 321, Naucalpan', 45, false, 7, true, 'No requiere recibos - pago de contado', NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (9, 'Luis Herrera Castro', 'luis.herrera@distribuidora.mx', '(55) 5545-6789', 'Luis Herrera', 'Distribuidora Regional', 'Av. Universidad 654, CDMX', 30, true, 14, true, 'Recordatorios cada 2 semanas', NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (10, 'Patricia Vega Ramírez', 'patricia@logistica.com.mx', '(55) 5523-4567', 'Patricia Vega', 'Logística Integral SA', 'Periférico Norte 987, Tlalnepantla', 21, true, 5, true, 'Cliente exigente - recordatorios cada 5 días', NULL, NULL, NULL, NULL, NULL, NULL, 'México', true, NULL),
  (11, 'FORTEQUIM', 'juan.rodriguez@pinturasdoalonline.onmicrosoft.com', NULL, 'Juan Manuel Rodríguez', 'FORTEQUIM', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '001', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (12, 'QUIMI-KAO', 'comprasjr@kao.com', NULL, 'Inti Campos', 'QUIMI-KAO', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '002', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (13, 'LUBYRECSA DE MEXICO', 'avillada@lubyrec.com', NULL, 'Abigail Villada', 'LUBYRECSA DE MEXICO', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '003', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (14, 'INGREDION MEXICO', 'Sofia.Orozco@ingredion.com', NULL, 'Sofia Orozco', 'INGREDION MEXICO', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '004', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (15, 'INDUSTRIAL DE PINTURAS ECATEPEC, S.A. DE C.V.', 'idiaz@ipesamex.com', NULL, 'Ivonne Díaz', 'INDUSTRIAL DE PINTURAS ECATEPEC, S.A. DE C.V.', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '005', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (16, 'INDUSTRIAL TECNICA DE PINTURAS', 'rafaelromero@pinturasacuario.com.mx', NULL, 'RAFAEL ROMERO', 'INDUSTRIAL TECNICA DE PINTURAS', NULL, 30, true, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '006', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (17, 'INDUSTRIAL QUIMICA ENERGETICA', 'contactoptq@gmail.com', NULL, 'David Alvarado', 'INDUSTRIAL QUIMICA ENERGETICA', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '007', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (18, 'APELSA MONTERREY', 'compras.insumos@rengra.com.mx', NULL, NULL, 'APELSA MONTERREY', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '008', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (19, 'PRODUCTOS SIGMA', 'luciacomprasigma@yahoo.com.mx', NULL, 'Lucia López', 'PRODUCTOS SIGMA', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '009', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (20, 'INDUSTRIALIZADORA OLEOFINOS', 'hilda.calderon@oleofinos.com.mx', NULL, 'Hilda Calderón', 'INDUSTRIALIZADORA OLEOFINOS', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '010', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (21, 'PINTURAS VALMEX', 'compras@pinturasvalmex.com', NULL, 'Juan Pablo García', 'PINTURAS VALMEX', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '012', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (22, 'CASMAN COMERCIALIZADORA INDUSTRIAL', 'emancera@casman.com.mx', NULL, 'Eduardo Mancera', 'CASMAN COMERCIALIZADORA INDUSTRIAL', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '013', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (23, 'INDUSTRIAL ACEITERA', 'rreyes@aceitera.com.mx', NULL, 'Guadalupe Del Rocio Reyes', 'INDUSTRIAL ACEITERA', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '014', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (24, 'TEAM FOODS MEXICO', 'carol.vazquez@alianzateam.com', NULL, 'Carol Vazquez Salas', 'TEAM FOODS MEXICO', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '017', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (25, 'MACROPOL', 'SRAMIREZ@macropol.com.mx', NULL, 'Susana Ramirez Vite', 'MACROPOL', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '018', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (26, 'ARMSTRONG LABORATORIOS DE MEXICO', 'martinezk@armstronglabs.com.mx', NULL, 'Karina Martínez', 'ARMSTRONG LABORATORIOS DE MEXICO', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '020', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (27, 'SURFAMEX', 'compras@surfamex.com', NULL, NULL, 'SURFAMEX', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '021', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (28, 'AOC MEXICANA DE RESINAS', 'Rodrigo.Delgado@aocformulations.com', NULL, 'Delgado, Rodrigo', 'AOC MEXICANA DE RESINAS', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '023', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (29, 'HIDRA QUIM', 'patricia.sanchez@hidraquim.mx', NULL, 'Patricia Sánchez', 'HIDRA QUIM', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '024', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (30, 'STEPAN CDMX', 'RAguilar@stepan.com', NULL, 'Rebeca Aguilar', 'STEPAN CDMX', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '025', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (31, 'COMERCIALIZACION PAKDU', 'comprasquimic@quimic.norvak.com', NULL, NULL, 'COMERCIALIZACION PAKDU', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '026', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (32, 'INDECOLOR', 'elizabeth@indecolor.com.mx', NULL, 'Elizabeth Salas', 'INDECOLOR', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '027', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (33, 'SANCHEZ', 'graciela.monroy@sanchez.com.mx', NULL, 'GRACIELA MONROY', 'SANCHEZ', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '028', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (34, 'SYMRISE', 'susy.monjaras2@symrise.com', NULL, 'Susy Monjarás', 'SYMRISE', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '029', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (35, 'GRUPO QUIMICO INDUSTRIAL DE TOLUCA', 'elena@megapoliester.com', NULL, 'Elena Romero', 'GRUPO QUIMICO INDUSTRIAL DE TOLUCA', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '030', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (36, 'KILKER', 'administracion@kilker.com.mx', NULL, NULL, 'KILKER', NULL, 30, false, 7, true, 'Importado desde Excel Orsega el 9/26/2025', 2, '031', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (37, 'GRUPO QUIMICO INDUSTRIAL DE TOLUCA', 'elena@megapoliester.com', NULL, 'Elena Romero', 'GRUPO QUIMICO INDUSTRIAL DE TOLUCA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '001', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (38, 'INDUSTRIAL TECNICA DE PINTURAS', 'rafaelromero@pinturasacuario.com.mx', NULL, 'RAFAEL ROMERO', 'INDUSTRIAL TECNICA DE PINTURAS', NULL, 30, true, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '002', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (39, 'SANCHEZ', 'graciela.monroy@sanchez.com.mx', NULL, 'GRACIELA MONROY', 'SANCHEZ', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '003', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (40, 'POLIFORMAS PLASTICAS', 'analistacompras@poliformas.mx', NULL, 'Efrén Arellano N.', 'POLIFORMAS PLASTICAS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '004', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (41, 'PINTURAS DOAL', 'juan.rodriguez@pinturasdoalonline.onmicrosoft.com', NULL, 'Juan Manuel Rodríguez', 'PINTURAS DOAL', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '005', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (42, 'PINTURAS MEXICANAS DE PUEBLA', 'compras@pintumex.com.mx', NULL, 'Graciela Pérez Torres', 'PINTURAS MEXICANAS DE PUEBLA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '006', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (43, 'INDUSTRIAL DE PINTURAS ECATEPEC', 'idiaz@ipesamex.com', NULL, 'Ivonne Díaz', 'INDUSTRIAL DE PINTURAS ECATEPEC', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '007', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (44, 'CIA SHERWIN WILLIAMS', 'Sarai.Tiburcio@sherwin.com.mx', NULL, 'Sarai Tiburcio', 'CIA SHERWIN WILLIAMS', NULL, 30, true, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '008', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (45, 'DANNA Y MONT', 'dannaymont@gmail.com', NULL, 'Roberto Martínez', 'DANNA Y MONT', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '009', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (46, 'PINTURAS OSEL', 'asistentedecompras@oselmail.com', NULL, 'Francisco Perez', 'PINTURAS OSEL', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '010', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (47, 'PINTURAS VALMEX', 'compras@pinturasvalmex.com', NULL, 'Juan Pablo García', 'PINTURAS VALMEX', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '011', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (48, 'REACCIONES QUIMICAS', 'lgarciac@reacciones.com', NULL, 'Lucy Edaena Garcia Carranza', 'REACCIONES QUIMICAS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '012', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (49, 'POLIMEROS Y PINTURAS ALSA', 'compras@alsa.com.mx', NULL, NULL, 'POLIMEROS Y PINTURAS ALSA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '013', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (50, 'DESARROLLOS QUIMICOS MUNDIALES', 'mdiaz@dequimsa.com', NULL, 'Mireya Diaz', 'DESARROLLOS QUIMICOS MUNDIALES', NULL, 30, true, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '014', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (51, 'POLYNT COMPOSITES MEXICO', 'Angelina.Saucedo@POLYNT.COM', NULL, 'Saucedo Angelina', 'POLYNT COMPOSITES MEXICO', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '015', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (52, 'IRMA LETICIA ESCAMILLA CAMPOS', 'LETY-ESCAMILLA@hotmail.com', NULL, 'Leticia Escamilla', 'IRMA LETICIA ESCAMILLA CAMPOS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '016', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (53, 'NOURYON CHEMICALS', 'abillan.romero@nouryon.com', NULL, 'Abillan Romero', 'NOURYON CHEMICALS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '017', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (54, 'AXALTA COATING SYSTEMS MEXICO', 'Pedro.Rodriguez@axalta.com', NULL, 'Pedro Rodriguez', 'AXALTA COATING SYSTEMS MEXICO', NULL, 30, true, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '018', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (55, 'PINTURAS AXEL', 'compras@zaak.mx', NULL, 'Gerardo Castro', 'PINTURAS AXEL', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '019', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (56, 'INDUSTRIAS CASLON', 'proveedores@caslon.com.mx', NULL, 'Lizette López', 'INDUSTRIAS CASLON', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '020', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (57, 'PLACOSA', 'Suzett.Garcia@eftec.com', NULL, 'Suzett Garcia', 'PLACOSA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '021', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (58, 'PASTICOLORI', 'compras@pazti.com', NULL, NULL, 'PASTICOLORI', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '022', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (59, 'COMPUESTOS EN FIBRA DE VIDRIO', 'compras@comfivisa.com.mx', NULL, NULL, 'COMPUESTOS EN FIBRA DE VIDRIO', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '023', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (60, 'PINTURAS G 3', 'compras@pinturasg3.com', NULL, NULL, 'PINTURAS G 3', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '024', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (61, 'SIKA MEXICANA', 'garza.nelly@mx.sika.com', NULL, 'Nelly Garza', 'SIKA MEXICANA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '025', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (62, 'PYOSA INDUSTRIAS', 'brendas@pyosa.com', NULL, 'Brenda Sánchez', 'PYOSA INDUSTRIAS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '026', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (63, 'PRODUCTOS RIVIAL', 'mayra.perez@prisa.mx', NULL, 'Mayra Janeth Perez Navarro', 'PRODUCTOS RIVIAL', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '027', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (64, 'VALSPAR ARIES COATINGS', 'Maria.G.Moreno@valspar.com', NULL, 'Maria G Moreno', 'VALSPAR ARIES COATINGS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '029', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (65, 'ADITIVOS PLASTICOS META', 'jesusqi@hotmail.com', NULL, 'Jesus E. .Hernandez R', 'ADITIVOS PLASTICOS META', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '030', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (66, 'PINTURAS BEREL', 'rgutierrez@berel.com', NULL, 'Ricardo Gutierrez Cavazos', 'PINTURAS BEREL', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '031', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (67, 'PINTUCOM', 'aortiz@pintolux.com.mx', NULL, 'Alejandra Ortiz', 'PINTUCOM', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '032', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (68, 'KILKER', 'administracion@kilker.com.mx', NULL, NULL, 'KILKER', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '033', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (69, 'OSCAR ALBERTO TORRES AGUILAR (FIBRECEN)', 'logistica@cindmx.com', NULL, NULL, 'OSCAR ALBERTO TORRES AGUILAR (FIBRECEN)', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '034', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (70, 'GENERAL PAINT', 'gpcompras@general-paint.com.mx', NULL, 'Patricia Aguilar', 'GENERAL PAINT', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '035', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (71, 'CASMAN COMERCIALIZADORA INDUSTRIAL', 'emancera@casman.com.mx', NULL, 'Eduardo Mancera', 'CASMAN COMERCIALIZADORA INDUSTRIAL', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '036', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (72, 'INDECOLOR', 'elizabeth@indecolor.com.mx', NULL, 'Elizabeth Salas', 'INDECOLOR', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '037', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (73, 'PINTURAS CASTHER', 'proveedores@casther.com', NULL, NULL, 'PINTURAS CASTHER', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '038', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (74, 'AOC MEXICANA DE RESINAS', 'Rodrigo.Delgado@aocformulations.com', NULL, 'Delgado, Rodrigo', 'AOC MEXICANA DE RESINAS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '039', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (75, 'DOMCCAR PINTURAS Y RECUBRIMIENTOS', 'comprasdomcar@gmail.com', NULL, NULL, 'DOMCCAR PINTURAS Y RECUBRIMIENTOS', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '040', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (76, 'SUSANA ROCIO GALINDO UREÑA (DISTRIBUIDORA DE RESIBAS)', 'distribuidoraderesinas3@gmail.com', NULL, NULL, 'SUSANA ROCIO GALINDO UREÑA (DISTRIBUIDORA DE RESIBAS)', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '041', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (77, 'PAZTI MAYA', 'admonmaya@pazti.com', NULL, NULL, 'PAZTI MAYA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '042', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (78, 'RESINAS Y BARNICES FLEKAM', 'Flekam@gmail.com', NULL, NULL, 'RESINAS Y BARNICES FLEKAM', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '043', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (79, 'RESINAS POLIESTER Y GELCOAT', 'contacto@resinasygelcoat.com.mx', NULL, NULL, 'RESINAS POLIESTER Y GELCOAT', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '044', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (80, 'ERIKA ISABEL CORONA BARRERA (STARHILL)', 'ecorona@pinturasstarhill.com', NULL, 'Erika Corona', 'ERIKA ISABEL CORONA BARRERA (STARHILL)', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '045', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (81, 'PINTURAS Y RECUBRIMIENTOS RAVTECH', 'asalazar@pinturasravtech.com', NULL, 'Alejandra Salazar', 'PINTURAS Y RECUBRIMIENTOS RAVTECH', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '046', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (82, 'GRUPO URETANOS FLEXIBLES', 'ek78r@hotmail.com>', NULL, 'Dany Garza Niño', 'GRUPO URETANOS FLEXIBLES', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '047', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (83, 'RAQUEL LOPEZ TLATELPA (REYCO)', 'holareyco@gmail.com', NULL, NULL, 'RAQUEL LOPEZ TLATELPA (REYCO)', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '048', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (84, 'FORESTAL LA REFORMA', 'gelizondo@grupolareforma.com', NULL, 'Gabriel Elizondo', 'FORESTAL LA REFORMA', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '049', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (85, 'QUIMICOS Y SOLVENTES E&R', 'general@eyrsa.com.mx', NULL, NULL, 'QUIMICOS Y SOLVENTES E&R', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '050', NULL, NULL, NULL, NULL, 'México', true, NULL),
  (86, 'SCORPIO RECUBRIMIENTOS INDUSTRIALES', 'scorpio_rec@hotmail.com', NULL, NULL, 'SCORPIO RECUBRIMIENTOS INDUSTRIALES', NULL, 30, false, 7, true, 'Importado desde Excel Dura International el 9/26/2025', 1, '051', NULL, NULL, NULL, NULL, 'México', true, NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  contact_person = EXCLUDED.contact_person,
  company = EXCLUDED.company,
  address = EXCLUDED.address,
  payment_terms = EXCLUDED.payment_terms,
  requires_receipt = EXCLUDED.requires_receipt,
  reminder_frequency = EXCLUDED.reminder_frequency,
  is_active = EXCLUDED.is_active,
  notes = EXCLUDED.notes,
  company_id = EXCLUDED.company_id,
  client_code = EXCLUDED.client_code,
  secondary_email = EXCLUDED.secondary_email,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  postal_code = EXCLUDED.postal_code,
  country = EXCLUDED.country,
  email_notifications = EXCLUDED.email_notifications,
  customer_type = EXCLUDED.customer_type;

